-- ==============================================================================
-- Copyright (c) 2024-2026 Yusron Efendi. All rights reserved.
-- Platform Architecture: AXTO (axto.io) - Sovereign AI Infrastructure
-- Author & Architect: Yusron Efendi <hallo@axto.io>
-- Proprietary and Confidential. Unauthorized copying is strictly prohibited.
-- ==============================================================================
-- ============================================================
-- Migration 0012: New Playbooks Batch 3 — 20 Additional Products
-- Run AFTER 0011_more_playbooks.sql
-- New coverage:
--   pc01 copywriting   → PR & Media Kit Builder
--   pc01 copywriting   → Video Sales Letter (VSL) Pack
--   pc01 copywriting   → Wellness Coach & Fitness Business Kit
--   pc02 business      → Consulting & Advisory Kit
--   pc02 business      → Negotiation & Deals Mastery
--   pc02 business      → Restaurant & Food Business Kit
--   pc03 content       → TikTok Content Machine
--   pc03 content       → LinkedIn Article & Newsletter Pro
--   pc04 legal-hr      → Compliance & Policy Generator
--   pc05 ecommerce     → Etsy & Handmade Seller Kit
--   pc06 saas-startup  → Product Hunt & App Launch Kit
--   pc06 saas-startup  → API & Developer Marketing Kit
--   pc07 education     → Corporate Training & L&D Kit
--   pc07 education     → Language Learning & Tutor Kit
--   pc08 career        → Executive Leadership Pack
--   pc08 career        → Remote & Freelance Job Hunter Kit
--   pc09 real-estate   → Airbnb & Short-Term Rental Kit
--   pc09 real-estate   → Commercial Real Estate Kit
--   pc10 data-analytics→ Business Intelligence & Reporting Kit
--   pc10 data-analytics→ Financial Modeling & Forecasting Kit
-- Run: wrangler d1 execute axto-db --file=cf-migrations/0012_playbooks_batch3.sql
-- ============================================================

INSERT OR IGNORE INTO playbooks (id,category_id,slug,name,subtitle,description,long_description,price_usd,original_price,prompt_count,icon,badge,file_format,r2_key,compatible_with,language,tags,preview_text,is_featured,is_active,sort_order) VALUES
('pb-copy-006','pc01','pr-media-kit-builder','PR & Media Kit Builder','20 prompts to get press coverage, podcast bookings & features','Press releases, media pitches, journalist outreach, podcast guest bios, HARO responses, and brand media kit copy.','20 prompts for PR-seeking founders and publicists. Press Releases (5 prompts — product launch, funding, partnership, award, executive hire), Media Pitching (5 prompts — news angle pitch, personal story pitch, data exclusive, trend commentary, expert source pitch), Podcast & Speaking (4 prompts — guest one-sheet bio, speaker intro, podcast pitch email, thought leadership angle), HARO & Reactive PR (3 prompts — HARO response, reactive media comment, crisis initial statement), Media Kit Assets (3 prompts — company boilerplate 3 lengths, founder bio, brand fact sheet).',19,34,20,'📰','','pdf','playbooks/pr-media-kit-builder.pdf','["chatgpt","claude","gemini"]','en','["pr","press","media","journalist","podcast","publicity"]','Prompt #1 — Product Launch Press Release: You are a PR director. Write a press release for [PRODUCT/COMPANY] with: Headline (under 100 chars), Dateline, Lead paragraph (who/what/where/when/why in 40 words), Body (2-3 paragraphs), CEO quote, Customer quote, Boilerplate, Media contact.',0,1,6),

('pb-copy-007','pc01','video-sales-letter-pack','Video Sales Letter (VSL) Pack','15 VSL scripts that convert — from 5-min shorts to 60-min webinars','Full VSL scripts for online courses, coaching programs, SaaS, physical products, and webinars.','15 complete VSL and webinar scripts on proven frameworks (PASTOR, AIDA, Problem-Agitate-Solve). Script Formats (5 prompts — 5-min product VSL, 15-min offer VSL, 30-min webinar, 45-min training+pitch webinar, 60-min masterclass pitch), Hook & Open Sequences (3 prompts — curiosity-based open, bold claim+proof, question-loop open), Story Architecture (3 prompts — founder journey, client transformation, origin story), Offer & Close Sequences (4 prompts — offer stack builder, risk reversal+guarantee, scarcity/urgency, objection-preemption close).',34,59,15,'🎥','HIGH VALUE','pdf','playbooks/video-sales-letter-pack.pdf','["chatgpt","claude","gemini"]','en','["vsl","webinar","sales","copywriting","video","conversion"]','Prompt #1 — 15-Minute Offer VSL: You are a direct response copywriter. Write a complete 15-min VSL script for [PRODUCT/OFFER] with timestamps: [0:00-0:45] Hook, [0:45-2:00] Agitate, [2:00-4:00] Story, [4:00-6:00] Proof, [6:00-9:00] Mechanism, [9:00-11:00] Offer, [11:00-12:30] Price, [12:30-13:30] Guarantee, [13:30-15:00] Close.',0,1,7),

('pb-copy-008','pc01','wellness-coach-fitness-biz-kit','Wellness Coach & Fitness Business Kit','25 prompts to attract clients, sell programs, and grow a health business','Coaching offer copy, fitness program sales pages, client intake, transformation frameworks, and wellness social media.','25 prompts for personal trainers, health coaches, nutritionists, yoga instructors. Offer & Sales Copy (6 prompts), Client Journey (5 prompts), Social Media (7 prompts), Business Growth (4 prompts), Compliance & Ethics (3 prompts). Includes guidance on ethical marketing in wellness.',19,34,25,'💪','','pdf','playbooks/wellness-coach-fitness-biz-kit.pdf','["chatgpt","claude","gemini"]','en','["wellness","fitness","health-coach","personal-trainer","nutrition","coaching"]','Prompt #1 — 1:1 Coaching Offer Page: You are a health copywriter. Write a coaching offer page for [SPECIALTY] coach. Structure: Headline (promise-based), Subheadline (who + outcome), Problem Section, Solution Reveal, What is Included, Results/Testimonials, Who it is For, Investment, FAQ, CTA.',0,1,8),

('pb-biz-005','pc02','consulting-advisory-kit','Consulting & Advisory Kit','25 prompts to sell, deliver, and scale your consulting practice','Discovery call scripts, engagement scoping, diagnostic frameworks, recommendation reports, and retainer pitches.','25 prompts for independent consultants and fractional executives. Business Development (6 prompts — discovery call script, consulting proposal, diagnostic assessment, capability statement, case study template, retainer offer), Delivery (8 prompts — kickoff workshop, current state assessment, gap analysis, recommendations report, implementation roadmap, stakeholder presentation, progress review, final summary+expansion), Frameworks (6 prompts — SWOT, market sizing, competitive landscape, operating model, change readiness, ROI business case), Client Communication (5 prompts).',29,49,25,'🧩','','pdf','playbooks/consulting-advisory-kit.pdf','["chatgpt","claude","gemini"]','en','["consulting","advisory","proposal","strategy","client","fractional"]','Prompt #1 — Discovery Call Script: You are a senior management consultant. Write a 45-min discovery call script for [PROSPECT TITLE]: [0-5min] Set context, [5-15min] Situation questions, [15-25min] Problem questions, [25-35min] Implication questions, [35-42min] Need-payoff, [42-45min] Next step.',0,1,5),

('pb-biz-006','pc02','negotiation-deals-mastery','Negotiation & Deals Mastery','20 prompts to negotiate salary, contracts, partnerships & vendors','Salary negotiation scripts, vendor rate reductions, partnership deal structures, contract clause counters, and lease negotiations.','20 prompts covering every high-stakes negotiation scenario. Salary & Compensation (5 prompts), Vendor & Supplier (4 prompts), Business Deals (5 prompts), Real Estate & Leases (3 prompts), Contracts & Terms (3 prompts). Every prompt uses principled negotiation — interests not positions, BATNA analysis, and anchoring.',19,29,20,'🤜','','pdf','playbooks/negotiation-deals-mastery.pdf','["chatgpt","claude","gemini"]','en','["negotiation","salary","contracts","vendor","deals","business"]','Prompt #1 — Salary Negotiation After Job Offer: Write a script for responding to a job offer. Include: gratitude opener, restate enthusiasm, the ask (state number then STOP), justification (market data + value), total comp reframe, close. Offer: [$X] | Target: [$Y] | Leverage: [COMPETING OFFER/SKILL]',0,1,6),

('pb-biz-007','pc02','restaurant-food-business-kit','Restaurant & Food Business Kit','25 prompts to open, market, and grow a food business','Menu descriptions, restaurant concept copy, Google Business posts, delivery listings, staff training, and review management.','25 prompts for restaurants, food entrepreneurs, caterers, ghost kitchens. Menu & Concept Copy (6 prompts), Digital Presence (6 prompts), Customer Experience (5 prompts), Review & Reputation (4 prompts), Operations & Staff (4 prompts).',19,34,25,'🍽️','','pdf','playbooks/restaurant-food-business-kit.pdf','["chatgpt","claude","gemini"]','en','["restaurant","food","menu","hospitality","catering","food-business"]','Prompt #1 — Menu Item Descriptions: You are a food copywriter. Write menu descriptions for [DISHES] at [RESTAURANT TYPE]. For each: 2-3 sentence description evoking sensory experience, key ingredients, allergen notes. Tone: [FINE DINING/CASUAL/FAST CASUAL/ETHNIC].',0,1,7),

('pb-content-004','pc03','tiktok-content-machine','TikTok Content Machine','30 prompts for viral scripts, hooks, and TikTok growth strategy','Native TikTok scripts, trending hooks, TikTok Shop product scripts, creator monetization copy, and niche content calendars.','30 prompts engineered for TikTok. Native Video Scripts (10 prompts — POV story, talking head rant, tutorial under 60s, day-in-my-life voiceover, green screen explainer, transformation reveal, things I wish I knew, controversy take, response to comment, collab/duet script), Hook Engineering (6 prompts), Growth Strategy (5 prompts), TikTok Shop & Monetization (5 prompts), Engagement & Community (4 prompts).',19,34,30,'🎵','NEW','pdf','playbooks/tiktok-content-machine.pdf','["chatgpt","claude","gemini"]','en','["tiktok","viral","video","social-media","creator","short-form"]','Prompt #1 — POV Story Video Script: Write a POV story for [NICHE]. Format: [HOOK first 3s]: POV: [relatable situation], [ACT 1 3-8s]: Set scene, [ACT 2 8-25s]: Rising tension, [TURN 25-35s]: Unexpected twist, [PAYOFF 35-50s]: Resolution, [CTA final 3s]. Tone: [FUNNY/EMOTIONAL/EDUCATIONAL]',1,1,4),

('pb-content-005','pc03','linkedin-article-newsletter-pro','LinkedIn Article & Newsletter Pro','20 prompts for long-form LinkedIn content that builds authority','LinkedIn article frameworks, newsletter issues, thought leadership essays, collaborative articles, and content repurposing.','20 prompts for LinkedIn long-form formats. LinkedIn Articles (7 prompts — thought leadership essay, career lessons post, industry prediction, case study write-up, contrarian take, how-I-did-it breakdown, open letter to industry), Newsletter Issues (7 prompts), Growth & Repurposing (6 prompts — talk→newsletter, podcast→article, thread→article, etc.).',19,29,20,'✍️','','pdf','playbooks/linkedin-article-newsletter-pro.pdf','["chatgpt","claude","gemini"]','en','["linkedin","article","newsletter","thought-leadership","content","authority"]','Prompt #1 — Thought Leadership Essay: You are a ghostwriter for executives. Write a LinkedIn article establishing [AUTHOR] as a thought leader on [TOPIC]. Structure: Headline (controversial claim), Hook (150 words, no "excited to share"), Thesis (1 sentence), Body (4-5 sections: conventional wisdom → why wrong → your framework → practice), Conclusion, CTA with specific question.',0,1,5),

('pb-legal-003','pc04','compliance-policy-generator','Compliance & Policy Generator','25 prompts for company policies, compliance docs & workplace procedures','Employee handbook sections, data protection policies, workplace safety, code of conduct, DEI policies, and remote work policies.','25 prompts for Operations Managers, HR Directors, and business owners. Employee Handbook Sections (8 prompts — code of conduct, attendance, PTO, expense, social media, conflicts of interest, whistleblower, disciplinary), Data & Privacy Compliance (5 prompts), Workplace Safety & Wellbeing (5 prompts), Operational Procedures (4 prompts), DEI & Culture (3 prompts). Includes plain-language summaries. NOTE: Review with a lawyer.',29,49,25,'📜','','pdf','playbooks/compliance-policy-generator.pdf','["chatgpt","claude","gemini"]','en','["compliance","policy","hr","gdpr","workplace","legal"]','Prompt #1 — Employee Code of Conduct: Write a comprehensive Code of Conduct for [COMPANY NAME]. Sections: Purpose and scope, Values and expected behaviors, Professional conduct, Conflicts of interest, Confidentiality, Use of company resources, Social media policy, Reporting violations + non-retaliation, Consequences, Acknowledgment statement. Tone: [FORMAL/APPROACHABLE]',0,1,3),

('pb-ecom-004','pc05','etsy-handmade-seller-kit','Etsy & Handmade Seller Kit','25 prompts to rank, convert, and scale your Etsy or handmade business','Etsy listing SEO, shop announcement, about page story, packaging insert messages, digital download descriptions, and craft fair booth copy.','25 prompts for Etsy sellers and handmade creators. Listing Optimization (8 prompts — title formula, description, digital download desc, personalized order, variations, shipping note, made-to-order disclaimer, gift upsell), Shop Setup (6 prompts), Marketing & Growth (5 prompts), Customer Experience (6 prompts). Includes Etsy SEO keyword framework.',19,34,25,'🧶','NEW','pdf','playbooks/etsy-handmade-seller-kit.pdf','["chatgpt","claude","gemini"]','en','["etsy","handmade","ecommerce","craft","digital-downloads","small-business"]','Prompt #1 — Etsy Listing Title Formula: Write an optimized listing title for [PRODUCT] for Etsy search. Rules: Front-load main keyword, include product type+material+style+occasion, 120-140 chars, use commas to separate phrases, avoid filler words. Product: [PRODUCT] | Material: [MATERIAL] | Buyer: [TARGET BUYER]',0,1,4),

('pb-saas-004','pc06','product-hunt-app-launch-kit','Product Hunt & App Launch Kit','20 prompts to launch your product, get #1 of the day, and sustain momentum','Product Hunt listing copy, App Store/Play Store listings, press kit copy, and post-launch email sequences.','20 prompts for founders launching on Product Hunt, App Store, Google Play. Product Hunt Listing (5 prompts — tagline generator, description, gallery captions, first maker comment, 5 response templates), App Store/Play Store (5 prompts), Pre-Launch & Day-Of (5 prompts), Post-Launch (5 prompts).',19,34,20,'🏹','','pdf','playbooks/product-hunt-app-launch-kit.pdf','["chatgpt","claude","gemini"]','en','["product-hunt","app-launch","saas","app-store","startup","launch"]','Prompt #1 — Product Hunt Tagline Generator: Write 10 tagline options for [PRODUCT]. Rules: under 60 chars, no buzzwords, instantly clear. 5 formats: (A) what it does, (B) who its for, (C) problem solved, (D) outcome-first, (E) comparison. Product: [NAME] | Core benefit: [VALUE] | User: [WHO]',0,1,4),

('pb-saas-005','pc06','api-developer-marketing-kit','API & Developer Marketing Kit','20 prompts to attract developers, write great docs, and build a dev community','Developer landing page copy, API docs style guide, getting started guides, changelog writing, and developer community posts.','20 prompts for API companies and DevRel teams. Developer Landing Page (4 prompts), Documentation & Content (6 prompts — Getting Started guide, SDK readme, API endpoint description, code examples, error message improvements, tutorial blog post), Community & DevRel (5 prompts), Launch & Growth (5 prompts — Product Hunt, HN Show HN, dev.to post, testimonial collection, integration announcement).',24,39,20,'⚙️','','pdf','playbooks/api-developer-marketing-kit.pdf','["chatgpt","claude","gemini"]','en','["api","developer","devrel","documentation","saas","technical-marketing"]','Prompt #1 — Developer Homepage Hero: Write the hero section for [PRODUCT] developer homepage. Dev copy rules: lead with what it DOES, show code snippet, no fluff, address time-to-first-value. Provide: H1 (under 10 words), subheadline (1-2 sentences), 3 value bullets, CTAs. Product: [NAME] | Function: [WHAT IT DOES]',0,1,5),

('pb-edu-003','pc07','corporate-training-ld-kit','Corporate Training & L&D Kit','25 prompts to design, deliver, and measure workplace learning programs','Training needs analysis, L&D program design, e-learning scripts, facilitator guides, skills gap assessments, and learning measurement frameworks.','25 prompts for L&D Managers and corporate trainers. Needs Analysis & Design (6 prompts), Content Development (7 prompts — e-learning script with branching scenarios, ILT facilitator guide, blended learning sequence, micro-video script, job aid, pre-work brief, post-training commitment tool), Delivery & Facilitation (5 prompts), Assessment & Measurement (4 prompts — Kirkpatrick Level 1-4), Stakeholder Management (3 prompts).',24,39,25,'🏢','','pdf','playbooks/corporate-training-ld-kit.pdf','["chatgpt","claude","gemini"]','en','["training","l-and-d","learning","corporate","hr","e-learning"]','Prompt #1 — Training Needs Analysis Questionnaire: Design a TNA questionnaire for [ROLE] at [COMPANY TYPE]. Sections: Current skills inventory (1-5 scale), Priority skills, Skills gap, Preferred learning formats, Time availability, Past training effectiveness, Performance obstacles, Manager perspective version. Role: [TITLE] | Business goal: [GOAL]',0,1,2),

('pb-edu-004','pc07','language-learning-tutor-kit','Language Learning & Tutor Kit','20 prompts to learn any language faster and build a tutoring business','AI conversation practice scripts, vocabulary acquisition frameworks, grammar explanations, immersion schedules, and tutoring session designs.','20 prompts for language learners and professional tutors. Accelerated Learning (7 prompts — 80/20 vocabulary acquisition, spaced repetition flashcard generator, contextual sentence builder, pronunciation framework, comprehensible input playlist, conversation practice script, immersion schedule), Tutoring Business (6 prompts), Grammar & Explanation (4 prompts), Content & Community (3 prompts).',14,24,20,'🌍','','pdf','playbooks/language-learning-tutor-kit.pdf','["chatgpt","claude","gemini"]','en','["language-learning","tutor","education","esl","polyglot","teaching"]','Prompt #1 — 80/20 Vocabulary Acquisition: Create the 80/20 vocabulary list for [TARGET LANGUAGE] for [USE CASE]. Generate: Top 100 high-frequency words organized by category with examples, 50 domain-specific words for [USE CASE], 20 power phrases for common social situations, learning order recommendation. Level: [BEGINNER/INTERMEDIATE]',0,1,3),

('pb-career-003','pc08','executive-leadership-pack','Executive Leadership Pack','25 prompts for C-suite communication, board relations, and executive presence','Board presentations, executive memos, company announcements, investor letters, all-hands scripts, and crisis communications for senior leaders.','25 prompts for C-suite executives and VPs. Strategic Communication (7 prompts — annual company narrative/state of business, quarterly all-hands script, vision memo, organizational change announcement, M&A communication, reorg announcement, mission/values articulation), Board & Investor Relations (5 prompts), Leadership Communication (7 prompts — crisis response, departure announcement, recognition email, performance culture memo, decision rationale, town hall Q&A prep, succession communication), Personal Brand (6 prompts).',29,49,25,'👑','','pdf','playbooks/executive-leadership-pack.pdf','["chatgpt","claude","gemini"]','en','["executive","leadership","ceo","board","communication","c-suite"]','Prompt #1 — State of the Business All-Hands Script: Write a compelling annual state-of-business narrative for [CEO] to deliver at all-hands. Structure: Opening (story from the year), Year in Review (honest — wins + challenges), Where We Stand (market position), Where We Going (3 priorities), What We Need from the Team, Close (personal + inspiring). Stage: [STARTUP/GROWTH/MATURE]',0,1,3),

('pb-career-004','pc08','remote-job-hunter-kit','Remote & Freelance Job Hunter Kit','20 prompts to land remote jobs and freelance clients from anywhere','Remote-optimized resume, async communication portfolio, remote work cover letters, Upwork/Toptal profiles, and remote interview preparation.','20 prompts for remote work job seekers and freelancers. Remote Resume & Profile (5 prompts — remote-optimized resume, Upwork profile optimizer, Toptal application essay, portfolio case study, LinkedIn open-to-work for remote), Remote Job Applications (5 prompts), Remote Interview Prep (4 prompts), Freelance Client Acquisition (6 prompts — Upwork cover letter, remote proposal, onboarding email x3, async update, off-platform transition).',14,24,20,'🌐','','pdf','playbooks/remote-job-hunter-kit.pdf','["chatgpt","claude","gemini"]','en','["remote-work","freelance","upwork","job-search","career","location-independent"]','Prompt #1 — Remote-Optimized Resume: Rewrite this resume for remote job applications. Optimizations: add remote tools (Notion/Slack/Loom), quantify self-management across time zones, replace office-centric language with async equivalents, add remote achievements (delivery rate, client satisfaction). Target: [JOB TITLE] | Timezone: [TZ] | Remote experience: [N years]',0,1,4),

('pb-re-003','pc09','airbnb-short-term-rental-kit','Airbnb & Short-Term Rental Kit','25 prompts to maximize occupancy, ratings, and revenue on Airbnb, VRBO & more','Listing titles, property descriptions, house rules, guest messaging sequences, review strategies, and superhost communication templates.','25 prompts for STR hosts on Airbnb, VRBO, Booking.com. Listing Creation (7 prompts — title formula, property description, room highlights, house rules, neighborhood guide, photo captions, amenity bullets), Guest Communication (8 prompts — booking confirmation, pre-arrival, check-in guide, mid-stay check-in, departure reminder, post-stay thank-you+review request, negative review response, inquiry conversion), Revenue & Pricing (4 prompts), Superhost & Operations (6 prompts).',19,34,25,'🏡','NEW','pdf','playbooks/airbnb-short-term-rental-kit.pdf','["chatgpt","claude","gemini"]','en','["airbnb","short-term-rental","vrbo","hosting","real-estate","property"]','Prompt #1 — Airbnb Listing Title Formula: Write 5 listing title options for [PROPERTY TYPE] in [LOCATION]. Rules: under 50 chars, lead with most searchable feature, avoid Cozy/Nice/Great, use power words (Sunlit/Lakefront/Private/Panoramic). Formats: Feature+Property, Style+Location, Emotion+Detail. Standout features: [TOP 3 FEATURES]',0,1,3),

('pb-re-004','pc09','commercial-real-estate-kit','Commercial Real Estate Kit','20 prompts for office, retail, industrial, and commercial property professionals','Tenant inquiry responses, LOI drafts, lease abstract summaries, commercial listing copy, broker outreach, and investment pitch decks.','20 prompts for commercial RE brokers, property managers, and investors. Leasing & Tenants (6 prompts — listing description office/retail/industrial, tenant inquiry+qualification, LOI draft outline, renewal proposal, TI allowance negotiation, anchor tenant announcement), Investment & Analysis (5 prompts), Broker & Client (5 prompts), Compliance & Operations (4 prompts — CAM reconciliation, estoppel, SNDA, environmental DD summary).',24,39,20,'🏙️','','pdf','playbooks/commercial-real-estate-kit.pdf','["chatgpt","claude","gemini"]','en','["commercial-real-estate","office","retail","leasing","investment","broker"]','Prompt #1 — Commercial Property Listing Description: Write a compelling listing description for [PROPERTY TYPE] at [LOCATION]. Sections: Headline (type+feature+location), Property Overview (size/class/condition), Location Advantage, Key Features (bullets), Available Space, Lease Terms, Contact. Type: [OFFICE/RETAIL/INDUSTRIAL] | Size: [SF] | Rate: [$/SF/YR]',0,1,3),

('pb-data-003','pc10','business-intelligence-reporting-kit','Business Intelligence & Reporting Kit','25 prompts to build dashboards, automate reports, and tell stories with data','KPI frameworks, dashboard design briefs, Power BI/Tableau narrative guides, executive report templates, and data storytelling.','25 prompts for BI Developers and data-driven managers. KPI & Metrics (5 prompts), Dashboard Design (5 prompts — executive dashboard brief, department dashboard spec, self-service requirements, dashboard critique, refresh schedule), Report Writing (6 prompts), Automation & Architecture (4 prompts), Stakeholder & Communication (5 prompts — presenting to skeptical executives, explaining methodology to non-technical audience, data literacy email series x3, BI adoption campaign, data governance policy).',24,39,25,'🗂️','','pdf','playbooks/business-intelligence-reporting-kit.pdf','["chatgpt","claude","gemini"]','en','["business-intelligence","dashboard","reporting","kpi","power-bi","data"]','Prompt #1 — KPI Definition Framework: Help me define and document a KPI for [METRIC NAME]. Template: 1. Metric name, 2. Definition (exact, no ambiguity), 3. Formula + data sources, 4. Owner, 5. Target, 6. Frequency, 7. Dimensions (slices), 8. Related metrics, 9. Failure modes (how could it be gamed). Metric: [NAME] | Dept: [DEPT] | Data source: [SOURCE]',0,1,4),

('pb-data-004','pc10','financial-modeling-forecasting-kit','Financial Modeling & Forecasting Kit','20 prompts for financial projections, scenario planning & investor-ready outputs','Revenue model narratives, unit economics, budget vs actual analysis, scenario modeling, and board-ready financial storytelling.','20 prompts for Finance Managers, CFOs, and FP&A analysts. Revenue Modeling (5 prompts — SaaS revenue model assumptions, e-commerce model (traffic×conversion×AOV), services utilization-based model, marketplace GMV model, unit economics one-pager), Budget & Forecast (5 prompts), Scenario Planning (4 prompts — 3-scenario narrative base/bull/bear, sensitivity analysis, Monte Carlo interpretation, break-even analysis), Investor & Board (4 prompts), Cashflow & Operations (2 prompts).',24,39,20,'💹','','pdf','playbooks/financial-modeling-forecasting-kit.pdf','["chatgpt","claude","gemini"]','en','["finance","forecasting","financial-model","fpa","startup","investor"]','Prompt #1 — SaaS Revenue Model Assumptions Narrative: Write the assumptions section for a SaaS revenue model for investors. Sections: 1. Model overview, 2. Key revenue drivers (acquisition/ACV/NRR), 3. Growth rate assumptions with evidence, 4. Churn assumptions, 5. Expansion assumptions, 6. Sensitivity (which assumptions matter most), 7. Risks. Stage: [PRE-REVENUE/EARLY/GROWTH] | ARR: [$X] | Target: [$Y in N years]',0,1,5);

-- ── New bundles for Batch 3 ─────────────────────────────────────────────────
INSERT OR IGNORE INTO playbook_bundles (id,slug,name,description,price_usd,original_price,playbook_ids,badge,is_featured,is_active,sort_order) VALUES
('bundle-legal','legal-hr-complete-bundle','Legal & HR Complete Bundle','Legal Document Vault + HR & Hiring Toolkit + Compliance & Policy Generator — run a legally solid, well-staffed operation.',69,121,'["pb-legal-001","pb-legal-002","pb-legal-003"]','SAVE 43%',0,1,8),
('bundle-agency','agency-consulting-bundle','Agency & Consulting Bundle','Freelancer Business Kit + Consulting & Advisory Kit + Meeting Mastery + Cold Outreach — run a premium service business.',69,111,'["pb-biz-003","pb-biz-005","pb-biz-004","pb-copy-004"]','NEW',1,1,9),
('bundle-solopreneur','solopreneur-ultimate-bundle','Solopreneur Ultimate Bundle','LinkedIn Brand Pro + Brand Voice Kit + Cold Outreach + Podcast & Newsletter + Social Media Engine — build a one-person media empire.',59,110,'["pb-career-002","pb-copy-005","pb-copy-004","pb-content-003","pb-copy-003"]','POPULAR',0,1,10),
('bundle-content-creator-pro','content-creator-pro-bundle','Content Creator Pro Bundle','YouTube Scripts + TikTok Machine + Podcast & Newsletter + LinkedIn Article Pro — master every video and text channel.',59,101,'["pb-content-002","pb-content-004","pb-content-003","pb-content-005"]','NEW',0,1,11),
('bundle-finance-data','finance-data-bundle','Finance & Data Bundle','Data Analyst Toolkit + Marketing Analytics + BI & Reporting Kit + Financial Modeling — total data mastery.',79,126,'["pb-data-001","pb-data-002","pb-data-003","pb-data-004"]','SAVE 37%',0,1,12),
('bundle-real-estate-pro','real-estate-pro-bundle','Real Estate Pro Bundle','RE Agent Kit + Property Investor Playbook + Airbnb STR Kit + Commercial RE Kit — dominate every real estate niche.',69,106,'["pb-re-001","pb-re-002","pb-re-003","pb-re-004"]','SAVE 35%',0,1,13);

-- Update mega bundle to reflect all 48 playbooks
UPDATE playbook_bundles
SET original_price = 775,
    description = 'Every single playbook in our catalog. Lifetime access to all 48 current playbooks across all 10 categories — 1,000+ prompts total.'
WHERE id = 'bundle-mega';

-- ── Verify ─────────────────────────────────────────────────────────────────
-- SELECT COUNT(*) FROM playbooks WHERE is_active=1;      -- Expected: 48
-- SELECT COUNT(*) FROM playbook_bundles WHERE is_active=1; -- Expected: 13+
